### ISSUE TITLE
Upgrade app-discussion to be compatible with XP 7

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-discussion#1]
http://wiki.enonic.com/display/dev/7.0+app+upgrade+guide

**Comment by poi33** [comment]
The problem i faced when trying to upgrade this app to XP is that it uses the "appersist" lib.

    var appersist = require('/lib/openxp/appersist');

This lib is a personal library made by Rune (one of our consultants) 
And he is on maternity leave. Was in contact with him about updating it. 
But that would be a bigger change (probably?) to his library and i don't have time to upgrade his library at the moment.
